name: WEB-EMSCRIPTEN

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  linux-emscripten:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Emscripten Install
        run: ./scripts/emscripten-install.sh || true

      - name: Emscripten Build
        run: ./scripts/emscripten-build.sh

      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # You may pin to the exact commit or the version.
        # uses: crazy-max/ghaction-github-pages@a117e4aa1fb4854d021546d2abdfac95be568a3a
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
        # Git domain (default github.com)
          #domain: # optional, default is github.com
          # GitHub repository where assets will be deployed (default $GITHUB_REPOSITORY)
          #repo: # optional
          # Git branch where assets will be deployed
          #target_branch: # optional, default is gh-pages
          # Create incremental commit instead of doing push force
          #keep_history: # optional, default is false
          # Allow an empty commit to be created
          #allow_empty_commit: # optional, default is true
          # Build directory to deploy
          build_dir: bin-emscripten/bin/
          # Whether to treat build_dir as an absolute path
          #absolute_build_dir: # optional, default is false
          # If enabled, the content of symbolic links will be copied
          #follow_symlinks: # optional, default is false
          # The committer name and email address
          #committer: # optional
          # The author name and email address
          #author: # optional
          # Commit message
          #commit_message: # optional
          # Write the given domain name to the CNAME file
          #fqdn: # optional
          # Allow Jekyll to build your site
          #jekyll: # optional, default is true
          # If enabled, nothing will be pushed
          #dry_run: # optional, default is false
          # Enable verbose output
          #verbose: # optional, default is false