name: WINDOWS

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  BUILD_TYPE: MinSizeRel
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  windows-native:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Configure CMake
        shell: cmd
        run: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=MinSizeRel -DENABLE_TEST_COVERAGE=OFF

      - name: Build
        shell: cmd
        run: cmake --build build --config MinSizeRel --parallel

      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}